---
    release: fddaq-develop

    type: fddaq

    base_release: dunedaq-develop

    fddaq:
        - name: rawdatautils
          version: "develop"
          commit: null
        - name: fddetdataformats
          version: "develop"
          commit: null
        - name: fdreadoutlibs
          version: "develop"
          commit: null
        - name: fdreadoutmodules
          version: "develop"
          commit: null
        - name: dpdklibs
          version: "develop"
          commit: null
        - name: hermesmodules
          version: "develop"
          commit: null
        - name: sspmodules
          version: "develop"
          commit: null
        - name: flxlibs
          version: "develop"
          commit: null
        - name: uhallibs
          version: "develop"
          commit: null
        - name: wibmod
          version: "develop"
          commit: null
        - name: ctbmodules
          version: "develop"
          commit: null
        - name: snbmodules
          version: "develop"
          commit: null
        - name: fddaqconf
          version: "develop"
          commit: null
        - name: daqsystemtest
          version: "develop"
          commit: null

    pymodules:
        - name: pip
          version: 23.2.1
          source:  pypi
        - name: aniso8601
          version: 9.0.1
          source:  pypi
        - name: anyconfig
          version: 0.9.11
          source:  pypi
        - name: anyio
          version: 3.6.2
          source:  pypi
        - name: anytree
          version: 2.8.0
          source:  pypi
        - name: attrs
          version: 22.2.0
          source:  pypi
        - name: bidict
          version: 0.21.4
          source:  pypi
        - name: bitarray
          version: 2.3.4
          source:  pypi
        - name: cachetools
          version: 5.1.0
          source:  pypi
        - name: certifi
          version: 2020.12.5
          source:  pypi
        - name: chardet
          version: 3.0.4
          source:  pypi
        - name: click
          version: 8.1.2
          source:  pypi
        - name: click-configfile
          version: 0.2.3
          source:  pypi
        - name: click-didyoumean
          version: 0.3.0
          source:  pypi
        - name: click-shell
          version: 2.1
          source:  pypi
        - name: colorama
          version: 0.4.4
          source:  pypi
        - name: commonmark
          version: 0.9.1
          source:  pypi
        - name: configparser
          version: 5.2.0
          source:  pypi
        - name: connectivityserver
          version: 1.0.0
          source:  github_DUNE-DAQ
        - name: deepdiff
          version: 6.3.1
          source:  pypi
        - name: docker
          version: 5.0.3
          source:  pypi
        - name: daq-assettools
          version: 1.1.0
          source:  github_DUNE-DAQ
        - name: drunc
          version: 0.3.0
          source:  github_DUNE-DAQ
        - name: druncschema
          version: 0.3.0
          source:  github_DUNE-DAQ
        - name: elisa-client-api
          version: 0.2.0
          source:  github_DUNE-DAQ
        - name: et-xmlfile
          version: 1.0.1
          source:  pypi
        - name: fastjsonschema
          version: 2.14.5
          source:  pypi
        - name: Flask
          version: 2.1.1
          source:  pypi
        - name: Flask-Cors
          version: 3.0.10
          source:  pypi
        - name: Flask-HTTPAuth
          version: 4.6.0
          source:  pypi
        - name: Flask-RESTful
          version: 0.3.9
          source:  pypi
        - name: future
          version: 0.18.2
          source:  pypi
        - name: gevent
          version: 22.10.2
          source:  pypi
        - name: gojsonnet
          version: 0.20.0
          source:  pypi
        - name: google-auth
          version: 2.6.6
          source:  pypi
        - name: graphviz
          version: 0.16
          source:  pypi
        - name: greenlet
          version: 2.0.2
          source:  pypi
        - name: gunicorn
          version: 20.1.0
          source:  pypi
        - name: h11
          version: 0.14.0
          source:  pypi
        - name: h5py
          version: 3.7.0
          source:  pypi
        - name: httpcore
          version: 0.16.3
          source:  pypi
        - name: httpx
          version: 0.23.3
          source:  pypi
        - name: idna
          version: "2.10"
          source:  pypi
        - name: importlib-metadata
          version: 4.11.3
          source:  pypi
        - name: iniconfig
          version: 1.1.1
          source:  pypi
        - name: integrationtest
          version: 1.9.1
          source:  github_DUNE-DAQ
        - name: itsdangerous
          version: 2.0.1
          source:  pypi
        - name: jdcal
          version: 1.4.1
          source:  pypi
        - name: Jinja2
          version: 3.1.1
          source:  pypi
        - name: jsonnet
          version: 0.16.0
          source:  pypi
        - name: jsonpointer
          version: "2.0"
          source:  pypi
        - name: jsonschema
          version: 4.17.3
          source:  pypi
        - name: kafka-python
          version: 2.0.2
          source:  pypi
        - name: kubernetes
          version: 23.6.0
          source:  pypi
        - name: markdown-it-py
          version: 2.2.0
          source:  pypi
        - name: MarkupSafe
          version: 2.0.1
          source:  pypi
        - name: mdurl
          version: 0.1.2
          source:  pypi
        - name: moo
          version: 0.6.7
          source:  github_brettviren
        - name: nanoid
          version: 2.0.0
          source:  pypi
        - name: nanorc
          version: 5.0.10
          source:  github_DUNE-DAQ
        - name: networkx
          version: 2.6.3
          source:  pypi
        - name: numpy
          version: 1.24.0
          source:  pypi
        - name: oauthlib
          version: 3.2.0
          source:  pypi
        - name: openpyxl
          version: 3.1.2
          source:  pypi
        - name: ordered-set
          version: 4.1.0
          source:  pypi
        - name: packaging
          version: "21.0"
          source:  pypi
        - name: pexpect
          version: 4.8.0
          source:  pypi
        - name: pluggy
          version: 0.13.1
          source:  pypi
        - name: protobuf
          version: 4.24.4
          source:  pypi
        - name: psutil
          version: 5.9.0
          source:  pypi
        - name: ptyprocess
          version: 0.7.0
          source:  pypi
        - name: py
          version: 1.10.0
          source:  pypi
        - name: pyasn1
          version: 0.4.8
          source:  pypi
        - name: pyasn1-modules
          version: 0.2.8
          source:  pypi
        - name: pydot
          version: 1.4.2
          source:  pypi
        - name: Pygments
          version: 2.14.0
          source:  pypi
        - name: pyparsing
          version: 2.4.7
          source:  pypi
        - name: pyrsistent
          version: 0.17.3
          source:  pypi
        - name: PySocks
          version: 1.7.1
          source:  pypi
        - name: pytest
          version: 7.3.2
          source:  pypi
        - name: python-dateutil
          version: 2.8.2
          source:  pypi
        - name: python-ipmi
          version: 0.5.1
          source:  pypi
        - name: pytz
          version: 2022.1
          source:  pypi
        - name: PyYAML
          version: "6.0"
          source:  pypi
        - name: pyzmq
          version: 22.3.0
          source:  pypi
        - name: requests
          version: 2.25.0
          source:  pypi
        - name: requests-oauthlib
          version: 1.3.1
          source:  pypi
        - name: rfc3986
          version: 1.5.0
          source:  pypi
        - name: rich
          version: 13.3.2
          source:  pypi
        - name: rsa
          version: 4.8
          source:  pypi
        - name: sh
          version: 1.14.1
          source:  pypi
        - name: six
          version: 1.16.0
          source:  pypi
        - name: sniffio
          version: 1.3.0
          source:  pypi
        - name: textual
          version: 0.10.1
          source:  pypi
        - name: toml
          version: 0.10.2
          source:  pypi
        - name: transitions
          version: 0.8.10
          source:  pypi
        - name: urllib3
          version: 1.26.5
          source:  pypi
        - name: websocket-client
          version: 1.3.2
          source:  pypi
        - name: Werkzeug
          version: 2.1.1
          source:  pypi
        - name: zipp
          version: 3.8.0
          source:  pypi
        - name: zmq
          version: 0.0.0
          source:  pypi
        - name: zope.event
          version: 4.6
          source:  pypi
        - name: zope.interface
          version: 5.5.2
          source:  pypi
