---
    release: develop

    externals:
        - name: cmake
          version: v3_17_2
          variant: ~
        - name: cetlib
          version: v3_10_00
          variant: ~
        - name: nlohmann_json
          version: v3_9_0b
          variant: ~
        - name: trace
          version: v3_15_09
          variant: ~
        - name: folly
          version: v2020_05_25
          variant: ~
        - name: ninja
          version: v1_10_0
          variant: ~
        - name: pyyaml
          version: v5_3_1
          variant: ~

    devtools:
        - name: pyyaml
          version: v5_3_1
          variant: ~

    systems:
        - name: pyyaml
          version: v5_3_1
          variant: ~

    packages:
        - name: ers
          version: v0_26_00c
          variant: ~
          depends_on: # list... 
