---
    release: dunedaq-develop

    type: dunedaq

    externals:
        - name: boost
          version: 1.77.0
          variant: "+context+container cxxstd=2a"
        - name: cetlib
          version: 3.18.01
          variant: "+lite"
        - name: trace
          version: 3.17.09
          variant: ~
        - name: nlohmann-json
          version: 3.9.0
          variant: ~
        - name: pistache
          version: dunedaq-v2.8.0
          variant: ~
        - name: highfive
          version: 2.7.1
          variant: "+mpi"
        - name: hdf5
          version: 1.12.0
          variant: "+mpi+threadsafe"
        - name: libarchive
          version: 3.6.2
          variant: ~
        - name: libzmq
          version: 4.3.4
          variant: ~
        - name: cppzmq
          version: 4.8.1
          variant: ~
        - name: msgpack-c
          version: 3.3.0
          variant: ~
        - name: py-pybind11
          version: 2.6.2
          variant: ~
        - name: uhal
          version: 2.8.1
          variant: ~
        - name: cpr
          version: 1.5.2
          variant: ~
        - name: librdkafka
          version: 1.7.0
          variant: ~
        - name: protobuf
          version: 4.24.4
          variant: ~
        - name: grpc
          version: 1.56.2
          variant: "cxxstd=17"
        - name: felix-software
          version: dunedaq-v4.2.0
          variant: ~
        - name: folly
          version: 2021.12.13.00
          variant: "cxxstd=2a"
        - name: fftw
          version: 3.3.10
          variant: "~mpi"
        - name: cli11
          version: 2.1.2
          variant: ~
        - name: krb5
          version: 1.19.2
          variant: ~
        - name: intel-tbb
          version: 2020.3
          variant: ~
        - name: dpdk
          version: 22.11
          variant: ~
        - name: fmt
          version: 8.1.1
          variant: "cxxstd=17 shared=True"
        - name: py-moo
          version: 0.6.7
          variant: ~
        - name: py-anyconfig
          version: 0.9.11
          variant: ~
        - name: py-jsonnet
          version: 0.16.0
          variant: ~
        - name: py-fastjsonschema
          version: 2.14.5
          variant: ~
        - name: rclone
          version: 1.64.0
          variant: ~
        - name: libtorrent
          version: 2.0.9
          variant: ~

    devtools:
        - name: cmake
          version: 3.23.1
          variant: ~
        - name: gdb
          version: 13.1 
          variant: "~python"
        - name: ninja
          version: 1.10.0
          variant: ~

    systems:
        - name: python
          version: 3.10.4
          variant: ~
        - name: gcc
          version: 12.1.0
          variant: "+binutils"
        - name: openssh
          version: 8.7p1
          variant: ~

    dunedaq:
        - name: daq-cmake
          version: v2.5.0
          commit: null
        - name: ers
          version: "develop"
          commit: null
        - name: logging
          version: "develop"
          commit: null
        - name: cmdlib
          version: "develop"
          commit: null
        - name: restcmd
          version: "develop"
          commit: null
        - name: opmonlib
          version: "develop"
          commit: null
        - name: rcif
          version: "develop"
          commit: null
        - name: appfwk
          version: "develop"
          commit: null
        - name: listrev
          version: "develop"
          commit: null
        - name: utilities
          version: "develop"
          commit: null
        - name: erskafka
          version: "develop"
          commit: null
        - name: kafkaopmon
          version: "develop"
          commit: null
        - name: ipm
          version: "develop"
          commit: null
        - name: serialization
          version: "develop"
          commit: null
        - name: iomanager
          version: "develop"
          commit: null
        - name: dfmessages
          version: "develop"
          commit: null
        - name: detdataformats
          version: "develop"
          commit: null
        - name: trgdataformats
          version: "develop"
          commit: null
        - name: detchannelmaps
          version: "develop"
          commit: null
        - name: daqdataformats
          version: "develop"
          commit: null
        - name: readoutlibs
          version: "develop"
          commit: null
        - name: readoutmodules
          version: "develop"
          commit: null
        - name: dfmodules
          version: "develop"
          commit: null
        - name: timing
          version: "develop"
          commit: null
        - name: timinglibs
          version: "develop"
          commit: null
        - name: daqconf
          version: "develop"
          commit: null
        - name: trigger
          version: "develop"
          commit: null
        - name: triggeralgs
          version: "develop"
          commit: null
        - name: hdf5libs
          version: "develop"
          commit: null
        - name: okssystem
          version: "develop"
          commit: null
        - name: oksdbinterfaces
          version: "develop"
          commit: null
        - name: oks
          version: "develop"
          commit: null
        - name: genconfig
          version: "develop"
          commit: null
        - name: oksutils
          version: "develop"
          commit: null
        - name: coredal
          version: "develop"
          commit: null
        - name: appdal
          version: "develop"
          commit: null
        - name: oksconfig
          version: "develop"
          commit: null
        - name: dbe
          version: "develop"
          commit: null
        - name: hsilibs
          version: "develop"
          commit: null

    others:
        - name: daq-release
          version: "develop"
          commit: null
        - name: daq-buildtools
          version: "develop"
          commit: null
        - name: daqsystemtest
          version: "develop"
          commit: null
        - name: pocket
          version: "develop"
          commit: null
        - name: microservices
          version: "develop"
          commit: null
        - name: dqm-backend
          version: "develop"
          commit: null
        - name: grafana-dashboards
          version: "develop"
          commit: null
